### ISSUE TITLE
Theory.js without require

### ISSUE THREAD

**Issue by badave** [amark/theory#2]
I was wondering if you could potentially separate the AMD portion of theory.js from the utility portion of theory.js.

Thanks!

**Comment by amark** [comment]
Yupe! Great idea - I should also make a configurable build service that allows you to build special versions of Theory, in the case you don't need various parts, like AMD. I'm gonna add this to the issue list.

Anyways, for now, I'll fix it up, but I need to know some specifics:

I try to pollute globals as little as possible, but to get things to work, I have to pollute some expected Nodejs stuff, which I will list here, please tell me which (or all) of these that need to not overwrite as to not break other libraries:
- window.root
- window.__dirname
- window.module
- window.exports
- window.module.exports
- window.require

**Comment by amark** [comment]
Per your suggestions via email, this fix is now done. Just do:

```
<script src="./theory.js">
root.opts.amd = false;
theory.com.off = true;
</script>
```

(you probably will want to turn communication off also)
